/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The list of contacts to reach the professional.
 */
export interface Contacts {
  title?: string;
  contacts?: ContactObject[];
  [k: string]: unknown;
}
export interface ContactObject {
  title: string;
  /**
   * A text representing the contact destination. Could be a phone number, an email, a link to a social media profile, etc.
   */
  contact?: string;
  type: "link" | "phone number" | "e-mail";
  [k: string]: unknown;
}
